[Component]
    Components = [
        { Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Product Catalog Service.productcatalogservice", Application = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"},
        { Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Product Catalog Service.productcatalogservice", Application = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;Labor Day Sale;1.2.10.0"}
    ]    
    Version = "1.2.2"
    ChartName = "chart/productcatalogservice"
    DockerRepo = "quay.io/hipsterstore/productcatalogservice"
    GitUrl = "https://github.com/ortelius/store-productcatalogservice"
    HelmChart = "GLOBAL.HelmChart"