[Component]
    Name = "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.productservice"
    Version = "1.2.2"
    ChartName = "chart/productservice"
    DockerRepo = "quay.io/hipsterstore/productservice"
    GitUrl = "https://github.com/ortelius/store-productservice"
    HelmChart = "GLOBAL.HelmChart"
    Applications = [
        "GLOBAL.Chasing Horses LLC.Vintage LLC.Hipster Store.Webstore;July 4th Sale;1.2.9.1"
    ]