[Component]
    Components = [
         { Name = "GLOBAL.SF Tech.Online Store Company.Store Services.Product Catalog Service.productcatalogservice", Application = "GLOBAL.SF Tech.Online Store Company.Hipster Store.Dev.Hipster Store;Labor Day Sale;1_2_10_2"}
    ]    
    Version = "1.2.2"
    ChartName = "chart/productcatalogservice"
    DockerRepo = "quay.io/hipsterstore/productcatalogservice"
    GitUrl = "https://github.com/ortelius/store-productcatalogservice"
    CustomAction = "GLOBAL.HelmChart"