apiVersion: v1
kind: Service
metadata:
  name: {{ include "productcatalogservice.name" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "productcatalogservice.name" . }}
  ports:
    - name: grpc
      port: 3550
      targetPort: 3550